const shortcuts = {
  'a': ['https://www.amazon.com/', 'amazon'],
  'd': ['https://docs.google.com/document/u/0/', 'google docs'],
  'e': ['https://godbolt.org/', 'compiler explorer'],
  'F': ['https://www.facebook.com/', 'facebook'],
  'f': ['https://www.facebook.com/messages/', 'messages'],
  'g': ['https://github.com/ivankp', 'github'],
  'G': ['https://github.com/ivankp?tab=repositories', 'github repos'],
  'h': ['https://home.nest.com/', 'nest'],
  'i': ['https://images.google.com/', 'google images'],
  'l': ['http://192.168.0.151/', 'bedroom light'],
  'm': ['https://mail.google.com/mail/u/0/#inbox', 'gmail'],
  'M': ['https://www.google.com/maps', 'google maps'],
  's': ['https://stackoverflow.com/users/2640636', 'stackoverflow'],
  't': ['https://docs.google.com/spreadsheets/u/0/', 'google spreadsheets'],
  'u': ['https://www.youtube.com/', 'youtube'],
  'U': ['https://www.youtube.com/feed/history', 'youtube history'],
  'w': ['https://www.wolframalpha.com/', 'wolframalpha'],
};
